



/**
 * CipherFlow — Full deployment script for Sepolia.
 * Auto-writes src/config/contracts.js when done.
 *
 * Run:  npx hardhat run scripts/deploy.js --network sepolia
 */

const { ethers } = require('ethers')
const fs   = require('fs')
const path = require('path')
require('dotenv').config()

console.log('RPC URL:', process.env.SEPOLIA_RPC_URL ? '✅ set' : '❌ missing')

const provider = new ethers.JsonRpcProvider(process.env.SEPOLIA_RPC_URL, {
  name: 'sepolia', chainId: 11155111,
})
const wallet = new ethers.Wallet(process.env.DEPLOYER_PRIVATE_KEY, provider)

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

// ── Helpers ───────────────────────────────────────────────────────────────────
function loadArtifact(contractName) {
  const artifactsDir = path.join(__dirname, '../artifacts/contracts')
  function find(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) { const f = find(full); if (f) return f }
      else if (entry.name === `${contractName}.json`) return full
    }
    return null
  }
  const p = find(artifactsDir)
  if (!p) throw new Error(`Artifact not found: ${contractName}. Run: npx hardhat compile`)
  return JSON.parse(fs.readFileSync(p, 'utf8'))
}

function makeFactory(name) {
  const a = loadArtifact(name)
  return new ethers.ContractFactory(a.abi, a.bytecode, wallet)
}

function makeContract(name, addr) {
  const a = loadArtifact(name)
  return new ethers.Contract(addr, a.abi, wallet)
}

async function deployContract(fac, args = [], retries = 3) {
  for (let i = 1; i <= retries; i++) {
    try {
      console.log(`  deploying (attempt ${i})…`)
      const c = await fac.deploy(...args)
      await c.waitForDeployment()
      return c
    } catch (e) {
      console.log(`  ⚠ attempt ${i} failed: ${e.message.slice(0, 120)}`)
      if (i === retries) throw e
      await sleep(6000)
    }
  }
}

async function sendTx(fn, retries = 3) {
  for (let i = 1; i <= retries; i++) {
    try {
      const t = await fn()
      await t.wait()
      return t
    } catch (e) {
      console.log(`  ⚠ tx attempt ${i} failed: ${e.message.slice(0, 80)}`)
      if (i === retries) throw e
      await sleep(6000)
    }
  }
}

function writeContractsJs(config) {
  const outPath = path.join(__dirname, '../../src/config/contracts.js')
  const content = `/**
 * Auto-generated by scripts/deploy.js — do not edit manually.
 * Re-run: npx hardhat run scripts/deploy.js --network sepolia
 */
export const DEPLOYED = ${JSON.stringify(config, null, 2)}

export const SEPOLIA_RPC = '${process.env.SEPOLIA_RPC_URL || ''}'
export const CHAIN_ID = 11155111
`
  fs.writeFileSync(outPath, content, 'utf8')
  console.log(`\n✅ Wrote ${outPath}`)
}

// ─────────────────────────────────────────────────────────────────────────────
async function main() {
  const bal = await provider.getBalance(wallet.address)
  console.log('Deployer:', wallet.address)
  console.log('Balance: ', ethers.formatEther(bal), 'ETH\n')

  if (bal < ethers.parseEther('0.05')) {
    throw new Error('Balance too low — need at least 0.05 ETH on Sepolia')
  }

  // Helper: convert human units to raw uint64
  // e.g. supply(6, 10_000_000) = 10_000_000 * 10^6
  const supply = (decimals, units) => BigInt(units) * (10n ** BigInt(decimals))

  const TokenFactory = makeFactory('CipherFlowToken')

  // ── 1. Deploy Tokens ───────────────────────────────────────────────────────
  // Constructor: (name, symbol, decimals, initialSupply)
  // initialSupply is passed as a plain uint64 — FHE.asEuint64() is called
  // inside the constructor, which works fine in the new @fhevm/solidity v0.9
  // contract (no library constructor restriction).
  console.log('── Deploying Tokens ──')

  const cUSDC = await deployContract(TokenFactory, [
    'Confidential USDC', 'cUSDC', 6, supply(6, 10_000_000)
  ])
  const cUSDCAddr = await cUSDC.getAddress()
  console.log('✅ cUSDC:', cUSDCAddr)
  await sleep(3000)

  const cUSDT = await deployContract(TokenFactory, [
    'Confidential USDT', 'cUSDT', 6, supply(6, 10_000_000)
  ])
  const cUSDTAddr = await cUSDT.getAddress()
  console.log('✅ cUSDT:', cUSDTAddr)
  await sleep(3000)

  const WBTC = await deployContract(TokenFactory, [
    'Wrapped Bitcoin', 'WBTC', 8, supply(8, 100)
  ])
  const WBTCAddr = await WBTC.getAddress()
  console.log('✅ WBTC: ', WBTCAddr)
  await sleep(3000)

  const BNB = await deployContract(TokenFactory, [
    'Binance Coin', 'BNB', 8, supply(8, 50_000)
  ])
  const BNBAddr = await BNB.getAddress()
  console.log('✅ BNB:  ', BNBAddr)
  await sleep(3000)

  const ZAMA = await deployContract(TokenFactory, [
    'Zama Token', 'ZAMA', 8, supply(8, 5_000_000)
  ])
  const ZAMAAddr = await ZAMA.getAddress()
  console.log('✅ ZAMA: ', ZAMAAddr)
  await sleep(3000)

  // ── 2. Deploy Swap ─────────────────────────────────────────────────────────
  console.log('\n── Deploying Swap ──')
  const swap = await deployContract(makeFactory('CipherFlowSwap'))
  const swapAddr = await swap.getAddress()
  console.log('✅ CipherFlowSwap:', swapAddr)
  await sleep(3000)

  // ── 3. Set exchange rates ──────────────────────────────────────────────────
  // RATE_SCALE = 1_000_000 (defined in CipherFlowSwap)
  // amountOut = (amountIn * rate) / RATE_SCALE
  // e.g. 1 cUSDC -> 1 cUSDT: rate = 1_000_000
  // e.g. 1 WBTC  -> 62000 cUSDC (8 dec -> 6 dec adjusted): rate = 62_000_000_000
  console.log('\n── Setting Rates ──')
  const swapContract = makeContract('CipherFlowSwap', swapAddr)

  const rates = [
    [cUSDCAddr, cUSDTAddr,  1_000_000n],
    [cUSDTAddr, cUSDCAddr,  1_000_000n],
    [WBTCAddr,  cUSDCAddr,  62_000_000_000n],
    [cUSDCAddr, WBTCAddr,   16n],
    [WBTCAddr,  cUSDTAddr,  62_000_000_000n],
    [cUSDTAddr, WBTCAddr,   16n],
    [ZAMAAddr,  cUSDCAddr,  2_500_000n],
    [cUSDCAddr, ZAMAAddr,   400_000n],
    [ZAMAAddr,  cUSDTAddr,  2_500_000n],
    [cUSDTAddr, ZAMAAddr,   400_000n],
    [BNBAddr,   cUSDCAddr,  580_000_000n],
    [cUSDCAddr, BNBAddr,    1_724n],
    [BNBAddr,   cUSDTAddr,  580_000_000n],
    [cUSDTAddr, BNBAddr,    1_724n],
    [WBTCAddr,  BNBAddr,    106_897_000n],
    [BNBAddr,   WBTCAddr,   9n],
    [WBTCAddr,  ZAMAAddr,   24_800_000_000n],
    [ZAMAAddr,  WBTCAddr,   40n],
    [BNBAddr,   ZAMAAddr,   232_000_000n],
    [ZAMAAddr,  BNBAddr,    4_310n],
  ]

  for (const [tIn, tOut, rate] of rates) {
    await sendTx(() => swapContract.setRate(tIn, tOut, rate))
    console.log(`  ✅ ${tIn.slice(0, 10)}→${tOut.slice(0, 10)} @ ${rate}`)
    await sleep(2000)
  }

  // ── 4. Deploy Factory + Pools ──────────────────────────────────────────────
  console.log('\n── Deploying Factory ──')
  const factoryContract = await deployContract(makeFactory('CipherFlowFactory'))
  const factoryAddr = await factoryContract.getAddress()
  console.log('✅ Factory:', factoryAddr)
  await sleep(3000)

  const poolPairs = [
    [cUSDCAddr, cUSDTAddr, 5n],
    [WBTCAddr,  cUSDCAddr, 30n],
    [ZAMAAddr,  cUSDCAddr, 30n],
    [BNBAddr,   cUSDCAddr, 30n],
  ]

  console.log('\n── Creating Pools ──')
  const poolAddresses = []
  for (const [t0, t1, fee] of poolPairs) {
    const t = await sendTx(() => factoryContract.createPool(t0, t1, fee))
    const receipt = await provider.getTransactionReceipt(t.hash)
    const event = receipt.logs
      .map(l => { try { return factoryContract.interface.parseLog(l) } catch { return null } })
      .find(e => e?.name === 'PoolCreated')
    const poolAddr = event?.args?.pool || '(error reading event)'
    poolAddresses.push(poolAddr)
    console.log(`  ✅ Pool ${t0.slice(0, 8)}/${t1.slice(0, 8)}:`, poolAddr)
    await sleep(2000)
  }

  // ── 5. Deploy Vaults ───────────────────────────────────────────────────────
  console.log('\n── Deploying Vaults ──')
  const VaultFactory = makeFactory('CipherFlowVault')
  const vaultDefs = [
    [cUSDCAddr, 'Alpha Vault',     'Delta Neutral',   1200n],
    [cUSDTAddr, 'Stable Shield',   'Yield Optimizer', 850n],
    [cUSDTAddr, 'Stable Shield 2', 'Basis Trade',     700n],
    [ZAMAAddr,  'Zama Deposit',    'Momentum',        2000n],
  ]

  const vaultAddresses = []
  for (const [asset, name, strat, apy] of vaultDefs) {
    const v = await deployContract(VaultFactory, [asset, name, strat, apy])
    const addr = await v.getAddress()
    vaultAddresses.push(addr)
    console.log(`  ✅ ${name}:`, addr)
    await sleep(3000)
  }

  // ── 6. Auto-write contracts.js ─────────────────────────────────────────────
  const config = {
    TOKENS:  { cUSDC: cUSDCAddr, cUSDT: cUSDTAddr, WBTC: WBTCAddr, BNB: BNBAddr, ZAMA: ZAMAAddr },
    SWAP:    swapAddr,
    FACTORY: factoryAddr,
    POOLS:   poolAddresses,
    VAULTS:  vaultAddresses,
  }

  writeContractsJs(config)

  console.log('\n═══════════════════════════════════════════════════')
  console.log('✅  ALL DONE — contracts.js has been auto-updated.')
  console.log('═══════════════════════════════════════════════════')
  console.log(JSON.stringify(config, null, 2))
}

main().catch(e => { console.error('\n❌ DEPLOY FAILED:\n', e.message); process.exit(1) })




